@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.wallev.coloniesmaidcitizen.init;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;